### ISSUE TITLE
Is there any way to make the mod work on a pre existing save or somehow re-make a save file to not lose progress?

### ISSUE THREAD

**Issue by Shadyaplay** [IronLucario2012/MaskMakerNotchesMod#2]

**Comment by IronLucario2012** [comment]
The mod works by injecting itself into the game at the point where a new savegame is created. As of now it would require a large amount of work to function in the way you're asking.

Not saying it never will, but at the moment, unfortunately, no.

**Comment by Shadyaplay** [comment]
Ok, thank you for replying.
