### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by DamageMaximo** [IronLucario2012/MaskMakerNotchesMod#3]
I installed the mod before creating a new save file, not playing a randomizer, but the Mask Maker's room has no charm notches for buying
here is the modlog, I only got to the Mask Maker's room more than 7 days after creating the save file.

[INFO]:[API] - Starting mod loading
[INFO]:[API] - Loading Global Settings
[INFO]:[API] - Deleting modlogs older than 7 days ago
[INFO]:[Benchwarp] - Initializing
[INFO]:[Benchwarp] - Loading Global Settings
[INFO]:[ConnectionMetadataInjector] - Initializing
[INFO]:[API] - Preloaded reflection in 2426ms
[INFO]:[CustomKnight] - Initializing
[INFO]:[CustomKnight] - Loading Global Settings
[INFO]:[DamageValues] - Initializing
[INFO]:[DamageValues] - Loading Global Settings
[INFO]:[DebugMod] - Initializing
[INFO]:[DebugMod] - Loading Global Settings
[INFO]:[ExtraMenuBackgrounds] - Initializing
[INFO]:[ExtraMenuBackgrounds] - Registering Menus
[INFO]:[GodSeekerPlus] - Initializing
[INFO]:[GodSeekerPlus] - Loading Global Settings
[INFO]:[HKMirrorMod] - Initializing
[INFO]:[ItemChangerMod] - Initializing
[INFO]:[ItemChangerMod] - Loading Global Settings
[INFO]:[MagicUIMod] - Initializing
[INFO]:[MagicUIMod] - Loading Global Settings
[INFO]:[MapChangerMod] - Initializing
[INFO]:[MaskMakerNotches] - Initializing
[INFO]:[MoreSaves] - Initializing
[INFO]:[MoreSaves] - Loading Global Settings
[INFO]:[Osmi] - Initializing
[INFO]:[QoL] - Initializing
[INFO]:[QoL] - Loading Global Settings
[INFO]:[RadiantMenu] - Initializing
[INFO]:[Satchel] - Initializing
[INFO]:[SFCoreMod] - Initializing
[INFO]:[SFCoreMod] - Loading Global Settings
[INFO]:[VanillaMapMod] - Initializing
[INFO]:[VanillaMapMod] - Loading Global Settings
[INFO]:[API] - Creating mod preloads
[WARN]:[API] - Could not find object "Particle System (1)" in scene "GG_Land_of_Storms", requested by mod `ExtraMenuBackgrounds`
[INFO]:[CustomKnight] - Initializing CustomKnight 2.1.1.0-1b3162
[INFO]:[CustomKnight] - [SwapManager] There are no folders in the Swap directory. No textures to Swap.
[INFO]:[GUI Controller] Building Help Text
[ERROR]:[API] - Failed to load Mod `Damage Values`
[ERROR]:[API] - System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight_Data\Managed\Mods\DamageValues'.
[ERROR]:[API] -   at System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) [0x000f7] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) [0x00006] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () [0x00054] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) [0x000d6] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0x00009] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.Directory.EnumerateFileSystemNames (System.String path, System.String searchPattern, System.IO.SearchOption searchOption, System.Boolean includeFiles, System.Boolean includeDirs) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.Directory.InternalEnumerateFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.Directory.EnumerateFiles (System.String path) [0x0000e] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at DamageValues.DamageValues.Initialize () [0x00000] in /home/runner/work/DamageValues/DamageValues/DamageValues.cs:24 
[ERROR]:[API] -   at Modding.Mod.Initialize (System.Collections.Generic.Dictionary`2[TKey,TValue] preloadedObjects) [0x00000] in <2b54cdaf7a934f0eb297d50c4090ea9f>:0 
[ERROR]:[API] -   at Modding.ModLoader.LoadMod (Modding.ModLoader+ModInstance mod, System.Boolean updateModText, System.Collections.Generic.Dictionary`2[TKey,TValue] preloadedObjects) [0x00022] in <2b54cdaf7a934f0eb297d50c4090ea9f>:0 
[INFO]:[DebugMod] - Initializing
[INFO]:[DebugMod] - Building MethodInfo dict...
[INFO]:[DebugMod] - Done! Time taken: 0,003643036s. Found 122 methods
[INFO]:[ExtraMenuBackgrounds] - Populating Menus
[INFO]:[HKMirrorMod] - Loading HKMirror Mod
[INFO]:[MaskMakerNotches] - Initializing MMN Mod
[INFO]:[MaskMakerNotches] - MMN Mod Initialized
[INFO]:[MoreSaves] - Initializing MoreSaves
[INFO]:[MoreSaves] - MoreSaves.Properties.Resources.resources
[INFO]:[MoreSaves] - MoreSaves.Resources.Input_BG.png
[INFO]:[MoreSaves] - Loaded image: Input_BG
[INFO]:[MoreSaves] - Initialized MoreSaves
[INFO]:[API] - Finished loading mods:
[INFO]:[API] - Modding API: 1.5.78.11833-72
[INFO]:[API] - Benchwarp : 3.2.1.0
[INFO]:[API] - CMICore : 2.1.8284.2438
[INFO]:[API] - CustomKnight : 2.1.1.0-1b3162
[INFO]:[API] - Damage Values : Failed to initialize! Check ModLog.txt
[INFO]:[API] - DebugMod : 1.4.9.10-a997ca
[INFO]:[API] - ExtraMenuBackgrounds : 1.0.0.0
[INFO]:[API] - GodSeekerPlus : 0.22.0
[INFO]:[API] - HKMirrorMod : v2.1.0.0
[INFO]:[API] - ItemChangerMod : 2.0.9+670
[INFO]:[API] - MagicUI : 1.6.8359.8221
[INFO]:[API] - MapChangerMod : 1.0.4
[INFO]:[API] - MaskMakerNotches : v1.2
[INFO]:[API] - MoreSaves : 0.7.9
[INFO]:[API] - Osmi : 0.2.0
[INFO]:[API] - QoL : 4.7.0.0-0a545b
[INFO]:[API] - Radiant Menu Theme : 1.5.1.0-b2331e
[INFO]:[API] - Satchel : 0.8.9-3f0575
[INFO]:[API] - SFCore : 1.5.5.0-048d12
[INFO]:[API] - VanillaMapMod : 2.0.1
[INFO]:[API] - 
[INFO]:[DebugMod] - [DREAM GATE] File dreamgate.dat not found!
[ERROR]:[UNITY] - NullReferenceException
[ERROR]:[UNITY] - UnityEngine.MonoBehaviour.StartCoroutine (System.Collections.IEnumerator routine) (at <047294ce45cf4b9a9441e48d2b8435e4>:0)
[ERROR]:[UNITY] - (wrapper dynamic-method) UnityEngine.UI.SaveSlotButton+<AnimateToSlotState>d__68.DMD<UnityEngine.UI.SaveSlotButton+<AnimateToSlotState>d__68::MoveNext>(UnityEngine.UI.SaveSlotButton/<AnimateToSlotState>d__68)
[ERROR]:[UNITY] - UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <047294ce45cf4b9a9441e48d2b8435e4>:0)
[ERROR]:[UNITY] - 
[ERROR]:[UNITY] - NullReferenceException
[ERROR]:[UNITY] - UnityEngine.Animator.ResetTrigger (System.String name) (at <d9588575c4ff4e818531b9dd12300bcd>:0)
[ERROR]:[UNITY] - (wrapper dynamic-method) UnityEngine.UI.SaveSlotButton+<AnimateToSlotState>d__68.DMD<UnityEngine.UI.SaveSlotButton+<AnimateToSlotState>d__68::MoveNext>(UnityEngine.UI.SaveSlotButton/<AnimateToSlotState>d__68)
[ERROR]:[UNITY] - UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <047294ce45cf4b9a9441e48d2b8435e4>:0)
[ERROR]:[UNITY] - UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
[ERROR]:[UNITY] - CoroutineQueue:Enqueue(IEnumerator)
[ERROR]:[UNITY] - UnityEngine.UI.SaveSlotButton:HideSaveSlot()
[ERROR]:[UNITY] - <HideSaveProfileMenu>d__216:DMD<UIManager+<HideSaveProfileMenu>d__216::MoveNext>(<HideSaveProfileMenu>d__216)
[ERROR]:[UNITY] - UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
[ERROR]:[UNITY] - 
[ERROR]:[UNITY] - NullReferenceException
[ERROR]:[UNITY] - UnityEngine.Animator.ResetTrigger (System.String name) (at <d9588575c4ff4e818531b9dd12300bcd>:0)
[ERROR]:[UNITY] - (wrapper dynamic-method) UnityEngine.UI.SaveSlotButton+<AnimateToSlotState>d__68.DMD<UnityEngine.UI.SaveSlotButton+<AnimateToSlotState>d__68::MoveNext>(UnityEngine.UI.SaveSlotButton/<AnimateToSlotState>d__68)
[ERROR]:[UNITY] - UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <047294ce45cf4b9a9441e48d2b8435e4>:0)
[ERROR]:[UNITY] - UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
[ERROR]:[UNITY] - CoroutineQueue:Enqueue(IEnumerator)
[ERROR]:[UNITY] - UnityEngine.UI.SaveSlotButton:HideSaveSlot()
[ERROR]:[UNITY] - <HideSaveProfileMenu>d__216:DMD<UIManager+<HideSaveProfileMenu>d__216::MoveNext>(<HideSaveProfileMenu>d__216)
[ERROR]:[UNITY] - UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
[ERROR]:[UNITY] - 
[INFO]:[CustomKnight] - HeroControllerStart
[INFO]:[CustomKnight] - [SwapManager] There are no folders in the Swap directory. No textures to Swap.
[INFO]:[CustomKnight] - skinable Geo : material is null
[INFO]:[CustomKnight] - [SwapManager] There are no folders in the Swap directory. No textures to Swap.
[WARN]:[DebugMod] - The key Escape has been unbound from Shade Spawn Points
[WARN]:[DebugMod] - The key Escape has been unbound from Toggle Vignette
[INFO]:[Benchwarp] - Saving Global Settings
[INFO]:[CustomKnight] - Saving Global Settings
[INFO]:[DamageValues] - Saving Global Settings
[INFO]:[DebugMod] - Saving Global Settings
[INFO]:[GodSeekerPlus] - Saving Global Settings
[INFO]:[ItemChangerMod] - Saving Global Settings
[INFO]:[MagicUIMod] - Saving Global Settings
[INFO]:[MoreSaves] - Saving Global Settings
[INFO]:[QoL] - Saving Global Settings
[INFO]:[SFCoreMod] - Saving Global Settings
[INFO]:[VanillaMapMod] - Saving Global Settings
[INFO]:[DebugMod] - Saving Global Settings
[INFO]:[DebugMod] - Saved
[INFO]:[API] - Saving Global Settings

**Comment by IronLucario2012** [comment]
Unfortunately, I can't say for sure what happened there. The charm notches are added to the world on initial save file creation, so they would have been in the first modlog.

Can you try starting a new save with the same mod setup, using debug or similar to get to the Mask Maker room to see if the notches are still missing, and if they are, attach the modlog from that run? I'm afraid there's not much I can do otherwise.

**Comment by DamageMaximo** [comment]
Well I did it, but this time the charm notches were there, I don't know why they aren't there on the main save file 'tho
here's the modlog

[INFO]:[API] - Starting mod loading
[INFO]:[API] - Loading Global Settings
[INFO]:[API] - Deleting modlogs older than 7 days ago
[INFO]:[Benchwarp] - Initializing
[INFO]:[Benchwarp] - Loading Global Settings
[INFO]:[ConnectionMetadataInjector] - Initializing
[INFO]:[API] - Preloaded reflection in 1622ms
[INFO]:[CustomKnight] - Initializing
[INFO]:[CustomKnight] - Loading Global Settings
[INFO]:[DamageValues] - Initializing
[INFO]:[DamageValues] - Loading Global Settings
[INFO]:[DebugMod] - Initializing
[INFO]:[DebugMod] - Loading Global Settings
[INFO]:[ExtraMenuBackgrounds] - Initializing
[INFO]:[ExtraMenuBackgrounds] - Registering Menus
[INFO]:[GodSeekerPlus] - Initializing
[INFO]:[GodSeekerPlus] - Loading Global Settings
[INFO]:[HKMirrorMod] - Initializing
[INFO]:[ItemChangerMod] - Initializing
[INFO]:[ItemChangerMod] - Loading Global Settings
[INFO]:[MagicUIMod] - Initializing
[INFO]:[MagicUIMod] - Loading Global Settings
[INFO]:[MapChangerMod] - Initializing
[INFO]:[MaskMakerNotches] - Initializing
[INFO]:[MoreSaves] - Initializing
[INFO]:[MoreSaves] - Loading Global Settings
[INFO]:[Osmi] - Initializing
[INFO]:[QoL] - Initializing
[INFO]:[QoL] - Loading Global Settings
[INFO]:[RadiantMenu] - Initializing
[INFO]:[Satchel] - Initializing
[INFO]:[SFCoreMod] - Initializing
[INFO]:[SFCoreMod] - Loading Global Settings
[INFO]:[VanillaMapMod] - Initializing
[INFO]:[VanillaMapMod] - Loading Global Settings
[INFO]:[API] - Creating mod preloads
[WARN]:[API] - Could not find object "Particle System (1)" in scene "GG_Land_of_Storms", requested by mod `ExtraMenuBackgrounds`
[INFO]:[CustomKnight] - Initializing CustomKnight 2.1.1.0-1b3162
[INFO]:[CustomKnight] - [SwapManager] There are no folders in the Swap directory. No textures to Swap.
[INFO]:[GUI Controller] Building Help Text
[ERROR]:[API] - Failed to load Mod `Damage Values`
[ERROR]:[API] - System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight_Data\Managed\Mods\DamageValues'.
[ERROR]:[API] -   at System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) [0x000f7] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) [0x00006] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () [0x00054] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) [0x000d6] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0x00009] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.Directory.EnumerateFileSystemNames (System.String path, System.String searchPattern, System.IO.SearchOption searchOption, System.Boolean includeFiles, System.Boolean includeDirs) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.Directory.InternalEnumerateFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.Directory.EnumerateFiles (System.String path) [0x0000e] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at DamageValues.DamageValues.Initialize () [0x00000] in /home/runner/work/DamageValues/DamageValues/DamageValues.cs:24 
[ERROR]:[API] -   at Modding.Mod.Initialize (System.Collections.Generic.Dictionary`2[TKey,TValue] preloadedObjects) [0x00000] in <2b54cdaf7a934f0eb297d50c4090ea9f>:0 
[ERROR]:[API] -   at Modding.ModLoader.LoadMod (Modding.ModLoader+ModInstance mod, System.Boolean updateModText, System.Collections.Generic.Dictionary`2[TKey,TValue] preloadedObjects) [0x00022] in <2b54cdaf7a934f0eb297d50c4090ea9f>:0 
[INFO]:[DebugMod] - Initializing
[INFO]:[DebugMod] - Building MethodInfo dict...
[INFO]:[DebugMod] - Done! Time taken: 0,002426147s. Found 122 methods
[INFO]:[ExtraMenuBackgrounds] - Populating Menus
[INFO]:[HKMirrorMod] - Loading HKMirror Mod
[INFO]:[MaskMakerNotches] - Initializing MMN Mod
[INFO]:[MaskMakerNotches] - MMN Mod Initialized
[INFO]:[MoreSaves] - Initializing MoreSaves
[INFO]:[MoreSaves] - MoreSaves.Properties.Resources.resources
[INFO]:[MoreSaves] - MoreSaves.Resources.Input_BG.png
[INFO]:[MoreSaves] - Loaded image: Input_BG
[INFO]:[MoreSaves] - Initialized MoreSaves
[INFO]:[API] - Finished loading mods:
[INFO]:[API] - Modding API: 1.5.78.11833-72
[INFO]:[API] - Benchwarp : 3.2.1.0
[INFO]:[API] - CMICore : 2.1.8284.2438
[INFO]:[API] - CustomKnight : 2.1.1.0-1b3162
[INFO]:[API] - Damage Values : Failed to initialize! Check ModLog.txt
[INFO]:[API] - DebugMod : 1.4.9.10-a997ca
[INFO]:[API] - ExtraMenuBackgrounds : 1.0.0.0
[INFO]:[API] - GodSeekerPlus : 0.22.0
[INFO]:[API] - HKMirrorMod : v2.1.0.0
[INFO]:[API] - ItemChangerMod : 2.0.9+670
[INFO]:[API] - MagicUI : 1.6.8359.8221
[INFO]:[API] - MapChangerMod : 1.0.4
[INFO]:[API] - MaskMakerNotches : v1.2
[INFO]:[API] - MoreSaves : 0.7.9
[INFO]:[API] - Osmi : 0.2.0
[INFO]:[API] - QoL : 4.7.0.0-0a545b
[INFO]:[API] - Radiant Menu Theme : 1.5.1.0-b2331e
[INFO]:[API] - Satchel : 0.8.9-3f0575
[INFO]:[API] - SFCore : 1.5.5.0-048d12
[INFO]:[API] - VanillaMapMod : 2.0.1
[INFO]:[API] - 
[INFO]:[ItemChangerMod] - Hooking ItemChanger.
[INFO]:[DebugMod] - [DREAM GATE] File dreamgate.dat not found!
[INFO]:[CustomKnight] - HeroControllerStart
[INFO]:[CustomKnight] - [SwapManager] There are no folders in the Swap directory. No textures to Swap.
[INFO]:[CustomKnight] - skinable Geo : material is null
[INFO]:[CustomKnight] - [SwapManager] There are no folders in the Swap directory. No textures to Swap.
[INFO]:[Benchwarp] - Saving Global Settings
[INFO]:[ItemChangerMod] - Unhooking ItemChanger.
[INFO]:[Benchwarp] - Saving Global Settings
[INFO]:[CustomKnight] - Saving Global Settings
[INFO]:[DamageValues] - Saving Global Settings
[INFO]:[DebugMod] - Saving Global Settings
[INFO]:[GodSeekerPlus] - Saving Global Settings
[INFO]:[ItemChangerMod] - Saving Global Settings
[INFO]:[MagicUIMod] - Saving Global Settings
[INFO]:[MoreSaves] - Saving Global Settings
[INFO]:[QoL] - Saving Global Settings
[INFO]:[SFCoreMod] - Saving Global Settings
[INFO]:[VanillaMapMod] - Saving Global Settings
[INFO]:[DebugMod] - Saving Global Settings
[INFO]:[DebugMod] - Saved
[INFO]:[API] - Saving Global Settings

**Comment by IronLucario2012** [comment]
That is definitely odd. If I had to guess I'd say whatever caused it to not load properly the first time might have updated between then and now?

Either way it sounds like the issue is fixed for future games of yours.

**Comment by DamageMaximo** [comment]
Yeah, thank you for helping though!
It's not like it ruined the savefile, I just need to add 6 charm notches and remove 6k Geo from the savefile to then pretend I bought them.
