### ISSUE TITLE
Mod still Not Working

### ISSUE THREAD

**Issue by Tindarushound** [IronLucario2012/MaskMakerNotchesMod#6]
The current module launcher is Lumafly.
The following screenshots are of other mods currently enabled

Note: I am a Chinese user, please forgive me if there are any translation grammatical problems.
![螢幕擷取畫面 2024-01-22 013601](https://github.com/IronLucario2012/MaskMakerNotchesMod/assets/157308159/ec173fef-fa0d-4034-ae69-3621a45d2424)
![螢幕擷取畫面 2024-01-22 013613](https://github.com/IronLucario2012/MaskMakerNotchesMod/assets/157308159/1df92316-6281-4858-bf96-14023612ba99)

**Comment by IronLucario2012** [comment]
Looking at that mod list, I don't think there's anything it conflicts with.

Can you give more details about how exactly it's not working?

**Comment by Tindarushound** [comment]
I have already opened a new save game to play.
But I didn’t find the trading option in the room.

**Comment by Tindarushound** [comment]
Maybe it requires not being able to exit the arrival room once you start the game to be effective?

**Comment by Tindarushound** [comment]
Too strange
I reopened two new archives and they were both there
We also tested the archive return interface and archive close operation.
![螢幕擷取畫面 2024-01-22 173513](https://github.com/IronLucario2012/MaskMakerNotchesMod/assets/157308159/59aa93fa-0e38-493b-b3e7-fa45a3861d74)
![螢幕擷取畫面 2024-01-22 173949](https://github.com/IronLucario2012/MaskMakerNotchesMod/assets/157308159/c96ed997-e6f4-441e-bd2b-1c214d41b1d9)
![螢幕擷取畫面 2024-01-22 175100](https://github.com/IronLucario2012/MaskMakerNotchesMod/assets/157308159/c351d5ff-181a-4e49-a11e-b58c11ac7bb3)
